// Closed set, shared with the client, so apps/web gets an exhaustive union and
// the compiler catches an unhandled case when a new code is added. Key and
// value match by design: call sites use ERROR_CODES.SLOT_TAKEN so a typo is a
// compile error rather than a string that silently never matches.
export const ERROR_CODES = {
  SLOT_TAKEN: "SLOT_TAKEN",
  SLOT_HELD: "SLOT_HELD",
  HOLD_EXPIRED: "HOLD_EXPIRED",
  VENUE_NOT_FOUND: "VENUE_NOT_FOUND",
  STATION_NOT_FOUND: "STATION_NOT_FOUND",
  PARTY_SIZE_EXCEEDS_CAPACITY: "PARTY_SIZE_EXCEEDS_CAPACITY",
  SLOT_COUNT_OUT_OF_RANGE: "SLOT_COUNT_OUT_OF_RANGE",
  IDEMPOTENCY_KEY_REUSED: "IDEMPOTENCY_KEY_REUSED",
  REQUEST_IN_FLIGHT: "REQUEST_IN_FLIGHT",
  IDEMPOTENCY_KEY_REQUIRED: "IDEMPOTENCY_KEY_REQUIRED",
  SLOT_NOT_ON_GRID: "SLOT_NOT_ON_GRID",
  SLOT_OUT_OF_WINDOW: "SLOT_OUT_OF_WINDOW",
  SLOT_UNAVAILABLE: "SLOT_UNAVAILABLE",
  DATE_OUT_OF_RANGE: "DATE_OUT_OF_RANGE",
  BOOKING_NOT_CANCELLABLE: "BOOKING_NOT_CANCELLABLE",
  HOLD_UNAVAILABLE: "HOLD_UNAVAILABLE",
  BOOKING_TIMEOUT: "BOOKING_TIMEOUT",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
  NOT_FOUND: "NOT_FOUND", // generic 404 for a route that matches no endpoint at all
  INTERNAL: "INTERNAL",
} as const;